Update Certify project code for Soc RSE membership
alan-turing-institute/REG-handbook pull request #113
Opened 2023-07-05 12:57 UTC by dsj976

Certify makes you to enter a project code when filling in the expenses form.

## Summary
I have updated the project code necessary to claim back the annual Soc RSE membership fee.

2023-07-05 13:46 UTC, JimMadge requested changes
Just a grammatical suggestion.

Should check with someone who knows whether this is the correct process.

2023-07-05 13:46 UTC, JimMadge commented on content/docs/onboarding/society_of_research_software_engineering.md
> +Use Certify to claim it back, and use the `R-RSE-001` project code when prompted.
```suggestion
Use Certify to claim it back and use the `R-RSE-001` project code when prompted.
```

I don't think commas are commonly used to separate independent clauses in (British) English.

2023-07-05 13:52 UTC, dsj976 commented
@martintoreilly could you confirm that this is the correct process to claim the Soc RSE annual membership fee on Certify?

2023-07-05 15:48 UTC, martintoreilly commented
> @martintoreilly could you confirm that this is the correct process to claim the Soc RSE annual membership fee on Certify?

Yes it is (see the REG open wiki page on [reclaiming expenses](https://github.com/alan-turing-institute/research-engineering-group/wiki/Reclaiming-out-of-pocket-expenses)). I've added the full text in the Certify project name / code drop down for ease of reference.

2023-07-05 15:51 UTC, martintoreilly commented
Do we want to cross-reference the REG open wiki (or just move the detail into the Handbook)? I'm not sure where the line is for things that are very Turing specific and not likely to be adopted / reused elsewhere and / or increasing risk of social engineering / exploitation of compromised credentials by openly documenting internal processes.

2023-07-06 08:42 UTC, dsj976 commented
> Do we want to cross-reference the REG open wiki (or just move the detail into the Handbook)? I'm not sure where the line is for things that are very Turing specific and not likely to be adopted / reused elsewhere and / or increasing risk of social engineering / exploitation of compromised credentials by openly documenting internal processes.

I personally think we should cross-reference the REG wiki here, no need to make project codes publicly available

2023-07-07 14:44 UTC, DavidBeavan commented
> Just a grammatical suggestion.

I'm not getting prescriptive here, but does the handbook have a style guide for language? Like a publication would? [The Guardian one](https://www.theguardian.com/guardian-observer-style-guide-a) is quite accessible.

2023-07-10 08:18 UTC, JimMadge commented
> > Just a grammatical suggestion.
> 
> I'm not getting prescriptive here, but does the handbook have a style guide for language? Like a publication would? [The Guardian one](https://www.theguardian.com/guardian-observer-style-guide-a) is quite accessible.

Not for language, spelling or grammar. There is some guidance on styling Markdown.

Feel free to propose one in a PR, it would be good to have an authority on what is right to remove the ambiguity. I don't think we want to write our own though.

The Guardian style doesn't seem so easy to navigate for grammatical questions. There is a lot about how to style the names of brands, people, organisations which isn't so useful here.

2023-07-11 08:49 UTC, dsj976 commented
I guess this PR is now ready to be merged? I will merge it by the end of the day, unless anyone has any reservations.

2023-07-11 10:05 UTC, JimMadge approved these changes

2023-07-19 09:12 UTC, merged